apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: exam-maximilianvanderschueren
  labels:
    createdBy: "Maximilian-Vanderschueren"

spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: lianvanderschueren/api-mv
          imagePullPolicy: Always
          name: api-demo
          ports:
            - containerPort: 8080
          resources: {}
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
          env:
            - name: NAME
              value: "Maximilian Vanderschueren"
            - name: DATE
              value: "today"
          volumeMounts:
            - name: config-volume
              mountPath: /mnt/config
              readOnly: true
              
      volumes:
        - name: config-volume
          configMap:
            name: backend-configmap

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30002
