apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: exam-maximilianvanderschueren
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: lianvanderschueren/frontend-mv
        ports:
        - containerPort: 30000
        env:
          - name: API_PORT
            valueFrom:
              configMapKeyRef:
                name: frontend-configmap
                key: API_PORT
          - name: API_HOST
            valueFrom:
              configMapKeyRef:
                name: frontend-configmap
                key: API_HOST
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - k3d-k3s-default-agent-2
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: exam-maximilianvanderschueren
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 30000
      nodePort: 30000
