version: '3.9'

services:
  web:
    image: python:3.12.0-alpine
    build:
      context: ./pointsApp
      dockerfile: Dockerfile
    networks:
      - web
      - database
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  db:
    image: postgres:16.1-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - database
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  web:
  database:

volumes:
  postgres_data: